spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
  messages:
    basename: messages.exception
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      host:
      port:
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: 10s
