spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
  jpa:
    show-sql: true
  messages:
    basename: messages.exception
  application:
    name: meeeka_project
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meeka_project?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      host: 192.168.198.128
      port: 6379
      password: bobo9778
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: 10s
server:
  port: 8009
